import React from 'react'
import pokedex from '../public/assets/pokedex.png'
import Image from 'next/image'
import { RiRadioButtonFill } from 'react-icons/ri'
import Link from 'next/link'
import Head from 'next/head'

const Holidaze = () => {
  return (
    <>
    <Head>
    <title>Portfolio | Pokedex</title>
    <meta name="description" content="Generated by create next app" />
    <link rel="icon" href="/favicon.ico" />
  </Head>
    <div className='w-full'>
        <div className='w-screen h-[30vh] lg:h-[40vh] relative'>
            <div className='absolute top-0 left-0 w-full h-[30vh] lg:h-[40vh] bg-black/70 z-10'></div>
            <Image 
            className='absolute z-1' 
            layout='fill' 
            objectFit='cover' 
            src={pokedex} 
            alt="/"
             />
            <div className='absolute top-[70%] max-w-[1240px] w-full left-[50%] right-[50%] translate-x-[-50%] translate-y-[-50%] text-white z-10 p-2'>
                <h2 className='py-2'>Pokedex</h2>
                <h3> Next.js / Tailwind</h3>
            </div>
        </div>
       
       <div className='max-w-[1240px] mx-auto p-2 grid md:grid-cols-5 gap-8 pt-8'>
         <div className='col-span-4'>
            <p>Project</p>
            <h2>Overview</h2>
            <h4 className='mt-4'>Functionalities</h4>
           <ul className='grid grid-cols-1 md:grid-cols-1'>
            <li className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/>Public Api deployed with Netlify</li>
            <li className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/>Render data from public Api</li>
            <li className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/>Pokemon Specific page</li>
            <li className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/>Hover over special effect</li>
   
     

           </ul>
            <a 
             href='https://coruscating-brioche-fbd852.netlify.app/'>
            <button className='px-8 py-2 mt-4 mr-8'>Demo</button>
            </a>
            <a
            href='https://github.com/Shumailakayani06/PokeDex-Next.js'>
            <button className='px-8 py-2 mt-4 mr-8'>Code</button>
            </a>
         </div>
         <div className='col-span-4 md:col-span-1 shadow-xl shadow-gray-400 rounded-xl p-4'>
            <div className='p-2'>
             <p className='text-center font-bold pb-2'>
                Technologies
             </p>
             <div className='grid grid-cols-3 md:grid-cols-1'>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/> React
                </p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/> Next.js
                </p>
                <p className='text-gray-600 py-2 flex items-center'><RiRadioButtonFill  className='pr-1'/> Tailwind
                </p>
             </div>
            </div>

         </div>
         <Link href="/#projects">
            <p className='underline cursor-pointer'>Back</p>
         </Link>
       </div>

    </div>
    </>
  )
}

export default Holidaze